title: Red River User Group
email: redriverusergroup@gmail.com
theme: jekyll-theme-tactile
domain: redriverusergroup.com
facebook: https://www.facebook.com/groups/21079809893/
slack: https://join.slack.com/t/redriverusergroups/shared_invite/enQtODk2NzM1MDMyNjc0LTJlOGFkNTZjYzFlYjFmYzBiNzU3ZTFhZGYxNTFiNDJhNDNjNGY2OTdhZjQwOTJiZTFhZmQ5ZGVjMjIzODBhYjU